In [2]:
import torch
print(torch.__version__)

2.2.0+cu118


# Introduction To tensors

## Creating Tensor

Pytorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
matrix = torch.tensor([[1,2],
                       [3,4]])

matrix

tensor([[1, 2],
        [3, 4]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
t = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])

t

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
t.ndim

3

In [15]:
t.shape

torch.Size([1, 3, 3])

In [16]:
t[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
t[0][1]

tensor([4, 5, 6])

### Random tensors

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

`Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [18]:
# Creating a random tensor of size (m,n)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5664, 0.9292, 0.2450, 0.4808],
        [0.4728, 0.4937, 0.7384, 0.2905],
        [0.0259, 0.7641, 0.1118, 0.8008]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.6529, 0.7633, 0.4714, 0.2226],
         [0.0746, 0.4976, 0.2641, 0.2026],
         [0.5572, 0.8456, 0.7029, 0.9639]],

        [[0.3255, 0.8817, 0.1252, 0.3111],
         [0.0117, 0.7016, 0.1070, 0.9873],
         [0.3071, 0.6085, 0.2191, 0.2659]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([2, 3, 4])

In [29]:
# Create a random tensor with similar shape to an image tensor
random_iamge_size = torch.rand([3,224,224]) # color channel, height, width
random_iamge_size

tensor([[[0.7236, 0.7435, 0.9553],
         [0.4772, 0.9711, 0.6469],
         [0.3082, 0.6591, 0.1303],
         ...,
         [0.9990, 0.8745, 0.2864],
         [0.3243, 0.0161, 0.5582],
         [0.9170, 0.5844, 0.2181]],

        [[0.6225, 0.0592, 0.2895],
         [0.6507, 0.7783, 0.7310],
         [0.4536, 0.4492, 0.5187],
         ...,
         [0.8559, 0.6079, 0.3254],
         [0.5429, 0.8631, 0.8195],
         [0.8176, 0.7521, 0.5650]],

        [[0.1497, 0.1992, 0.1570],
         [0.6243, 0.8051, 0.3715],
         [0.4726, 0.8116, 0.2855],
         ...,
         [0.7476, 0.9627, 0.0700],
         [0.2048, 0.1475, 0.9561],
         [0.5924, 0.7058, 0.1869]],

        ...,

        [[0.2697, 0.9348, 0.7267],
         [0.6315, 0.1092, 0.7059],
         [0.1531, 0.1441, 0.9946],
         ...,
         [0.0262, 0.3618, 0.2535],
         [0.1953, 0.0319, 0.5035],
         [0.7888, 0.7738, 0.4985]],

        [[0.7910, 0.0190, 0.4542],
         [0.0813, 0.6039, 0.8978],
         [0.