In [50]:
import torch
print(torch.__version__)

2.2.0+cu118


# Introduction To tensors

## Creating Tensor

Pytorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [51]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [52]:
scalar.ndim

0

In [53]:
scalar.shape

torch.Size([])

In [54]:
# Get tensor back as python int
scalar.item()

7

In [55]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [56]:
vector.ndim

1

In [57]:
vector.shape

torch.Size([2])

In [58]:
# Matrix
matrix = torch.tensor([[1,2],
                       [3,4]])

matrix

tensor([[1, 2],
        [3, 4]])

In [59]:
matrix.ndim

2

In [60]:
matrix.shape

torch.Size([2, 2])

In [61]:
# Tensor
t = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])

t

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [62]:
t.ndim

3

In [63]:
t.shape

torch.Size([1, 3, 3])

In [64]:
t[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
t[0][1]

tensor([4, 5, 6])

### Random tensors

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

`Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [66]:
# Creating a random tensor of size (m,n)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0682, 0.6754, 0.4420, 0.0742],
        [0.7414, 0.4658, 0.9959, 0.5576],
        [0.6511, 0.3967, 0.9403, 0.4016]])

In [67]:
random_tensor.ndim

2

In [68]:
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.7663, 0.9063, 0.1981, 0.5278],
         [0.9078, 0.7270, 0.5073, 0.3770],
         [0.2589, 0.0312, 0.0615, 0.7356]],

        [[0.8165, 0.4984, 0.5409, 0.6961],
         [0.5567, 0.8179, 0.0312, 0.8304],
         [0.8926, 0.6691, 0.9435, 0.6585]]])

In [69]:
random_tensor.ndim

3

In [70]:
random_tensor.shape

torch.Size([2, 3, 4])

In [71]:
# Create a random tensor with similar shape to an image tensor
random_iamge_size = torch.rand([3,224,224]) # color channel, height, width
random_iamge_size

tensor([[[0.3798, 0.5230, 0.0200,  ..., 0.2324, 0.3031, 0.7422],
         [0.2783, 0.8677, 0.2631,  ..., 0.7332, 0.6846, 0.9757],
         [0.9745, 0.8218, 0.9938,  ..., 0.0976, 0.9420, 0.6319],
         ...,
         [0.1963, 0.3809, 0.8148,  ..., 0.6228, 0.0956, 0.3589],
         [0.3183, 0.7614, 0.0949,  ..., 0.4021, 0.3086, 0.2881],
         [0.7401, 0.8595, 0.9699,  ..., 0.0141, 0.6018, 0.0364]],

        [[0.1701, 0.0033, 0.6877,  ..., 0.0787, 0.5215, 0.9741],
         [0.2633, 0.4061, 0.8993,  ..., 0.5959, 0.6014, 0.9810],
         [0.5210, 0.3667, 0.1889,  ..., 0.6011, 0.7288, 0.7683],
         ...,
         [0.4875, 0.4422, 0.7839,  ..., 0.5196, 0.3458, 0.1271],
         [0.3322, 0.7291, 0.0355,  ..., 0.2560, 0.4499, 0.0275],
         [0.8704, 0.0589, 0.0126,  ..., 0.1153, 0.4636, 0.1769]],

        [[0.8889, 0.1549, 0.5141,  ..., 0.0105, 0.2928, 0.9635],
         [0.9296, 0.8181, 0.1785,  ..., 0.4799, 0.1634, 0.8268],
         [0.4036, 0.0968, 0.7497,  ..., 0.4259, 0.5320, 0.

### Zeros and Ones

In [72]:
# Create a tensor all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [73]:
zeros.dtype

torch.float32

In [74]:
# Create a tensor all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [75]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

`Use torch.range() and get deprecated massage, use torch.arange()`

In [76]:
# torch.range()
one_to_ten = torch.range(start=1, end=11, step=1)
one_to_ten

C:\Users\Utsho Dey\AppData\Local\Temp\ipykernel_7908\328263437.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start=1, end=11, step=1)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [77]:
# torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
# Creating tensors zeros_like()
ten_zeors = torch.zeros_like(input=one_to_ten)
ten_zeors

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [79]:
# Creating tensors ones_like()
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with Pytorch & deep learning.
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

Tensor Datatypes - https://pytorch.org/docs/stable/tensors.html


In [80]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what datatype is the tensor (e.g float32 or float16)
                               device = None, # what device is your tensor on
                               requires_grad=False # weather or not to track gradients with this tensors operations
                               )

float_32_tensor

tensor([3., 6., 9.])

In [81]:
float_32_tensor.dtype

torch.float32

In [82]:
# Float 32 tensor
float_16_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [83]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [84]:
# Int 32 tensor
int_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [85]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (attributes)

1. Tensors not right datatypes - to get datatype from tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from tensor, can use `tensor.device`


In [86]:
#  Create a tensor
test = torch.rand(3,4)
test

tensor([[0.1945, 0.2843, 0.9366, 0.6486],
        [0.1972, 0.9724, 0.1854, 0.3861],
        [0.1384, 0.6434, 0.0459, 0.5930]])

In [87]:
# Find out details about the test tensor
print(test)
print(f'Datatype of tensor : {test.dtype}')
print(f'Shape of tensor : {test.shape}')
print(f'Device of tensor : {test.device}')

tensor([[0.1945, 0.2843, 0.9366, 0.6486],
        [0.1972, 0.9724, 0.1854, 0.3861],
        [0.1384, 0.6434, 0.0459, 0.5930]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multipication (element wise)
- Division
- Matrix multiplication

In [88]:
# Creating tensor and add operations
tensor = torch.tensor([1,2,3])

print(tensor+10) # add 10 to it
print(tensor-10) # substract 10 to it
print(tensor*10) # multipication 10 to it
print(tensor/10) # division 10 to it

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [89]:
# Creating tensor and add operations using PyTorch in-built functions
tensor = torch.tensor([1,2,3])

print(torch.add(tensor,10)) # add 10 to it
print(torch.subtract(tensor,10)) # substract 10 to it
print(torch.mul(tensor,10)) # multipication 10 to it
print(torch.divide(tensor,10)) # division 10 to it

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


### Matrix multipication

Two main ways of performing multipication in neural networks and deep learning
- Element-wise multipication
- Matrix multipicaiton (dot product)

There are two main rules that performing matrix multipication needs to satisfy:
- The **inner dimentions** must match:
    - `(3, 2) @ (3, 2) won't work`
    - `(2, 3) @ (3, 2) will work`
    - `(3, 2) 2 (2, 3) will work`

- The resulting matrix has the shape of the **outer dimentions**:
    - `(3, 2) @ (2, 3) -> (3, 3)`
    - `(2, 3) @ (3, 2) -> (2, 2)`

More info about multipications - https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [90]:
# Element wise multipication
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [91]:
# Matrix multipication
torch.matmul(tensor, tensor)

tensor(14)

In [92]:
# Matrix multipication by hand
1*1 + 2*2 + 3*3

14

In [93]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]
print(value)

tensor(6)
CPU times: total: 0 ns
Wall time: 1 ms


In [94]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning (shape errors)

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [95]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between `tensor_A` and `tensor_B` by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

- `torch.transpose(input, dim0, dim1)` - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
- `tensor.T` - where `tensor` is the desired tensor to transpose.

In [47]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

In [48]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [49]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [96]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Without the transpose, the rules of matrix mulitplication aren't fulfilled and we get an error like above.

How about a visual? 

![visual demo of matrix multiplication](https://github.com/UtshoDeyTech/Python-Programming/tree/main/00.%20Python%20Modules/raw/main/images/00-matrix-multiply-crop.gif)

You can create your own matrix multiplication visuals like this at http://matrixmultiplication.xyz/.

> **Note:** A matrix multiplication like this is also referred to as the [**dot product**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) of two matrices.

Neural networks are full of matrix multiplications and dot products.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `A`.

$$
y = x\cdot{A^T} + b
$$

Where:
* `x` is the input to the layer (deep learning is a stack of layers like `torch.nn.Linear()` and others on top of each other).
* `A` is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "`T`", that's because the weights matrix gets transposed).
  * **Note:** You might also often see `W` or another letter like `X` used to showcase the weights matrix.
* `b` is the bias term used to slightly offset the weights and inputs.
* `y` is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like $y = mx+b$ in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features` below and see what happens.

Do you notice anything to do with the shapes?