### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Import NumPy

In [28]:
import numpy
# import numpy as np

### 1. Examples

In [29]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2. Checking Numpy Version

In [31]:
print(np.__version__)

1.26.1


# Creating Arrays

In [32]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [33]:
# Use a tuple to create a NumPy array:
arr = np.array((1, 2, 3, 4, 5))

print(arr)


[1 2 3 4 5]


In [34]:
# 0-D arrays

arr = np.array(42)
# 0-D array with value of 42
print(arr)

42


In [35]:
# 1-D Arrays
"""An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array. These are the most common and basic arrays."""

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [36]:
# 2-D Arrays
"""An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors."""

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [37]:
# 3-D arrays
"""An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor."""

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [38]:
# np.ones
"""Create an (M x N) size array with full of 1 values."""

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
# np.zeros
"""Create an (M x N) size array with full of 0 values."""

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
# np.empty
""" Create an uninitialized (M x N) size array, filled with garbage values / 0 values."""

np.empty((2, 3))


array([[0.85478751, 0.4616302 , 0.14353567],
       [0.34271011, 1.50684719, 0.25156562]])

In [41]:
# np.eye
"""Create a 2D identity matrix with ones on the diagonal and zeros elsewhere."""

np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
# np.arange
"""Create a 1D array with a range of values from start (inclusive) to stop (exclusive) with a specified step."""

np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [43]:
# np.linspace
"""Create a 1D array with evenly spaced values between start and stop, with a specified number of elements."""

np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [44]:
# np.logspace
"""Create a 1D array with values spaced evenly on a logarithmic scale within a specified range."""

np.logspace(0, 3, 4)


array([   1.,   10.,  100., 1000.])

In [45]:
# np.full
"""Create a 2D array with all elements set to a specified value (e.g., 7)."""

np.full((3, 4), 7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [46]:
# np.random.randint
"""Create a 1D array with random integers within a specified range."""

np.random.randint(1, 10, 5)


array([8, 6, 1, 7, 5])

In [47]:
# np.random.random
"""Create a 2D array with random values from range 0-1"""

np.random.random((3, 4))

array([[0.23541718, 0.08295899, 0.51518257, 0.15881185],
       [0.59566342, 0.33427719, 0.175509  , 0.75015246],
       [0.54776323, 0.02625008, 0.55122218, 0.13994982]])

In [48]:
# np.random.randn
"""Create a 2D array with random values from a standard normal distribution (mean=0, std=1)."""

np.random.randn(2, 3)


array([[ 2.21974349,  0.51748814,  0.42669521],
       [-0.89644215,  0.19095773,  0.40304491]])

### Numpy Data-type

In [49]:
# float dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [50]:
# int dtype
np.array([1,2,3],dtype=int)

array([1, 2, 3])

In [51]:
# complex dtype
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [52]:
# boolean dtype
np.array([0,1,2,3],dtype=bool) # numpy treat all non zero value as True

array([False,  True,  True,  True])

### Check Number of Dimensions:

In [53]:
""" NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have. """

a = np.array(42)
b = np.array([1, 2, 3, 4],dtype=np.int32)
c = np.array([[1, 2, 3], [4, 5, 6]],dtype=int)
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],dtype=float)

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Check Array Shape:

In [54]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(4,)
(2, 3)
(2, 2, 3)


### Check Array Size:

In [55]:
print(a.size)
print(b.size)
print(c.size)
print(d.size)

1
4
6
12


### Check Array Item Size:
How many byte use an array for memory

In [56]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)
print(d.itemsize)

4
4
4
8


### Higher Dimensional Arrays

In [57]:
""" An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the ndmin argument. """

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Array Indexing

In [58]:
arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[2] + arr[3])

1
2
7


In [59]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2
5th element on 2nd row:  10


In [60]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [61]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('Last element from 2nd dim: ', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10


# Array Slicing


Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [ start : end ].

We can also define the step, like this: [ start : end : step ].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1



### Slicing 1-D Arrays

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])
print(arr[:4])

[5 6 7]
[1 2 3 4]


In [64]:
# Negative Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [65]:
# STEP
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])
print(arr[::2])


[2 4]
[1 3 5 7]


### Slicing 2-D Arrays

In [66]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [67]:
print(arr[:, 1:4])

[[2 3 4]
 [7 8 9]
 [7 8 9]]


In [68]:
print(arr[0:3, 2])

[3 8 8]


In [69]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# Data Types

### Data Types in Python
By default Python have these data types:

- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )


In [70]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [71]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [72]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [73]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [74]:
# arr = np.array(['a', '2', '3'], dtype='i')

### Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [75]:
arr = np.array([1.1, 2.1, 3.1])
print(arr)
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
[1 2 3]
int32


In [76]:
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [77]:
arr = np.array([1, 0, 3, 2])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True  True]
bool


# NumPy Array Copy vs View

### The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

### Copy :
The copy SHOULD NOT be affected by the changes made to the original array.

In [78]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


### VIEW :
- The view SHOULD be affected by the changes made to the original array.
- The original array SHOULD be affected by the changes made to the view.

In [79]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [80]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


### Check if Array Owns its Data

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [81]:
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

# The copy returns None.
# The view returns the original array.

None
[31  2  3  4  5]


# Array Shape

In [82]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [83]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# Array Arranging
It works as python range() function.

In numpy the function is arange(start,end,step) default step=1

In [84]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

# Array Reshaping
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [86]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [87]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.



In [89]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# Array Iterating


In [90]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [91]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)
        


for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [92]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)


for x in arr:
  for y in x:
    for z in y:
      print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element :

In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [93]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### Iteration Using ndenumerate()

In [94]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [95]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining Array

In [96]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [97]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[1 2 5 6]
 [3 4 7 8]]


### Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [98]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)
      
arr = np.stack((arr1, arr2), axis=0)
print(arr)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


### Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.


In [99]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.

In [100]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Height (depth)
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [101]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting Array

In [102]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [103]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [104]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [105]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


# Searching Arrays
ou can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [106]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [107]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [108]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


### Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [109]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)
print(x)

1


In [110]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [111]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


# Sorting Arrays

In [112]:
arr = np.array([3, 2, 0, 1])

#  This method returns a copy of the array, leaving the original array unchanged.
print(np.sort(arr))

[0 1 2 3]


In [113]:
arr = np.array(['banana', 'cherry', 'apple'])

# Sort the array alphabetically
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [114]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [115]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filter Array

In [116]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [117]:
# Creating the Filter Array
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


# Aritmetic Operation

In [118]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [119]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [121]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [122]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])