# Random Numbers in NumPy

In [1]:
from numpy import random

In [2]:
x = random.randint(100)
# Generate a random integer from 0 to 100:
print(x)

43


In [3]:
x = random.rand()
# Generate a random float from 0 to 1:
print(x)

0.8679776717853925


In [4]:
x=random.randint(100, size=(5))
# Generate a 1-D array containing 5 random integers from 0 to 100:
print(x)

[ 4 11 69 18  6]


In [5]:
x = random.randint(100, size=(3, 5))
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
print(x)

[[34 95 90 46 44]
 [13 91 69 33 38]
 [16  8 72  7  3]]


In [6]:
x = random.rand(5)
# Generate a 1-D array containing 5 random floats:
print(x)

[0.89965258 0.91109263 0.16194756 0.62286579 0.69532635]


In [7]:
x = random.rand(3, 5)
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
print(x)

[[0.66945475 0.83948177 0.03012093 0.15267778 0.45289078]
 [0.33397498 0.46175254 0.64334266 0.26320141 0.57540727]
 [0.32174349 0.84875241 0.38892322 0.35373678 0.17413287]]


In [8]:
x = random.choice([3, 5, 7, 9])
# The choice() method allows you to generate a random value based on an array of values.
# The choice() method takes an array as a parameter and randomly returns one of the values.
print(x)

9


In [9]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
print(x)

[[9 3 9 9 3]
 [7 9 5 5 7]
 [5 7 7 3 5]]


# Random Data Distribution

In [10]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[7 5 7 5 7 5 5 7 7 7 7 5 7 7 5 7 7 7 7 5 5 7 7 3 7 7 7 5 7 7 7 7 7 7 5 7 7
 5 3 7 3 7 5 7 7 7 7 7 7 7 5 7 7 7 5 3 7 7 5 7 7 7 5 7 7 7 5 5 7 7 5 7 7 7
 5 3 5 7 5 7 7 5 7 5 7 5 7 7 3 7 5 5 5 7 5 7 7 7 7 5]


In [11]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5)) # size (3,5) means 3 rows & 5 columns

print(x)

[[7 7 7 3 3]
 [7 5 7 7 7]
 [7 7 5 7 7]]
