# Random Numbers in NumPy

In [4]:
from numpy import random

In [8]:
x = random.randint(100)
# Generate a random integer from 0 to 100:
print(x)

18


In [9]:
x = random.rand()
# Generate a random float from 0 to 1:
print(x)

0.8068936287840797


In [11]:
x=random.randint(100, size=(5))
# Generate a 1-D array containing 5 random integers from 0 to 100:
print(x)

[39 11 68 32 12]


In [12]:
x = random.randint(100, size=(3, 5))
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
print(x)

[[27 73 55  1 85]
 [77 54 58 52  6]
 [84 23 77  6 23]]


In [13]:
x = random.rand(5)
# Generate a 1-D array containing 5 random floats:
print(x)

[0.3617855  0.3146708  0.65330222 0.20177156 0.9920235 ]


In [14]:
x = random.rand(3, 5)
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
print(x)

[[0.14335021 0.20215725 0.45680408 0.37041544 0.55303736]
 [0.45652609 0.78998073 0.52071316 0.9733598  0.5170296 ]
 [0.9897563  0.32744332 0.31264155 0.72011672 0.22272593]]


In [15]:
x = random.choice([3, 5, 7, 9])
# The choice() method allows you to generate a random value based on an array of values.
# The choice() method takes an array as a parameter and randomly returns one of the values.
print(x)

5


In [16]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
print(x)

[[3 5 5 9 3]
 [7 7 5 5 3]
 [3 7 9 5 3]]


# Random Data Distribution

In [5]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[5 5 7 5 7 7 5 7 7 7 7 5 7 5 5 7 5 7 5 7 5 5 5 5 7 7 5 5 3 7 5 3 7 5 7 7 5
 7 7 5 5 3 7 7 5 7 7 5 5 7 7 7 7 7 3 7 7 7 7 5 7 5 5 5 7 7 7 3 3 5 3 7 7 5
 5 7 7 7 7 7 5 7 3 7 5 7 7 7 5 5 7 3 7 3 5 3 3 5 7 5]


In [7]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5)) # size (3,5) means 3 rows & 5 columns

print(x)

[[7 7 5 5 7]
 [5 7 7 5 7]
 [3 5 7 7 3]]
